apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  USER_ID: dXN1YXJpb1Rlc3Rl # Valor em Base64 (ex.: echo -n "usuarioTeste" | base64)
  PASSWORD: c2VuaGFUZXN0ZQ== # Valor em Base64 (ex.: echo -n "senhaTeste" | base64)
